#!/usr/bin/env Rscript
# Wrapper script for edgeR GenePattern module
# Perform Differential expression using Quasi-Likelihood Pipeline, run glmQLFit() and glmQLFTest().
#
# Generated by GenePattern Module Toolkit

# Load required libraries with error checking
suppressPackageStartupMessages({
  library(optparse)
  library(edgeR)
})

# Define command line options
option_list <- list(
  make_option(c('--count.matrix.file'), type='character', default=NULL, 
              help='Input count matrix file with genes as rows and samples as columns'),
  make_option(c('--sample.groups.file'), type='character', default=NULL, 
              help='Two-column tab-delimited file specifying sample group assignments'),
  make_option(c('--comparison.groups'), type='character', default=NULL, 
              help='Comma-separated pair of group names to compare'),
  make_option(c('--output.prefix'), type='character', default='edgeR_results',
              help='Prefix for all output files'),
  make_option(c('--min.count'), type='integer', default=1,
              help='Minimum count threshold for gene filtering'),
  make_option(c('--min.samples'), type='integer', default=2,
              help='Minimum number of samples that must express a gene'),
  make_option(c('--norm.method'), type='character', default='TMM',
              help='Normalization method for calculating effective library sizes'),
  make_option(c('--robust.estimation'), type='logical', default=TRUE,
              help='Use robust estimation methods'),
  make_option(c('--abundance.trend'), type='logical', default=TRUE,
              help='Model the abundance-dependent trend'),
  make_option(c('--poisson.bound'), type='logical', default=TRUE,
              help='Apply Poisson bound to quasi-likelihood p-values'),
  make_option(c('--fdr.threshold'), type='double', default=0.05,
              help='False Discovery Rate threshold'),
  make_option(c('--fold.change.threshold'), type='double', default=1.0,
              help='Minimum absolute log2 fold change threshold'),
  make_option(c('--top.genes'), type='integer', default=100,
              help='Number of top differentially expressed genes'),
  make_option(c('--create.plots'), type='logical', default=TRUE,
              help='Generate diagnostic and results visualization plots')
)

# Parse arguments
opt_parser <- OptionParser(
  usage = "%prog [options]",
  option_list = option_list,
  description = "edgeR wrapper for GenePattern - Differential gene expression analysis using quasi-likelihood methods"
)
opt <- parse_args(opt_parser)

# Validate inputs
validate_inputs <- function(opt) {
  if (is.null(opt$count.matrix.file) || !file.exists(opt$count.matrix.file)) {
    stop("Count matrix file is required and must exist")
  }
  
  if (is.null(opt$sample.groups.file) || !file.exists(opt$sample.groups.file)) {
    stop("Sample groups file is required and must exist")
  }
  
  if (is.null(opt$comparison.groups)) {
    stop("Comparison groups must be specified")
  }
  
  return(TRUE)
}

# Load data
load_count_matrix <- function(file_path) {
  if (grepl("\\.gct$", file_path, ignore.case = TRUE)) {
    # Handle GCT format
    lines <- readLines(file_path)
    data_start <- 3  # Skip header lines
    counts <- read.table(text = paste(lines[data_start:length(lines)], collapse = "\n"), 
                        header = TRUE, sep = "\t", row.names = 1, check.names = FALSE)
    counts <- counts[, -1]  # Remove description column
  } else {
    # Handle regular tab-delimited or CSV
    sep_char <- ifelse(grepl("\\.csv$", file_path, ignore.case = TRUE), ",", "\t")
    counts <- read.table(file_path, header = TRUE, sep = sep_char, row.names = 1, 
                        check.names = FALSE, stringsAsFactors = FALSE)
  }
  
  # Convert to numeric matrix
  counts <- as.matrix(counts)
  counts[is.na(counts)] <- 0
  
  return(counts)
}

load_sample_groups <- function(file_path) {
  groups <- read.table(file_path, header = FALSE, sep = "\t", stringsAsFactors = FALSE)
  colnames(groups) <- c("sample", "group")
  return(groups)
}

# Run edgeR analysis
run_edger_analysis <- function(opt) {
  tryCatch({
    cat("Loading data...\n")
    
    # Load count matrix and sample groups
    counts <- load_count_matrix(opt$count.matrix.file)
    sample_info <- load_sample_groups(opt$sample.groups.file)
    
    # Parse comparison groups
    comp_groups <- unlist(strsplit(opt$comparison.groups, ","))
    if (length(comp_groups) != 2) {
      stop("Comparison groups must contain exactly two group names separated by comma")
    }
    
    # Filter samples to include only those in comparison groups
    sample_info <- sample_info[sample_info$group %in% comp_groups, ]
    counts <- counts[, colnames(counts) %in% sample_info$sample, drop = FALSE]
    
    # Align sample order
    sample_info <- sample_info[match(colnames(counts), sample_info$sample), ]
    
    cat("Creating DGEList object...\n")
    
    # Create DGEList object
    y <- DGEList(counts = counts, group = factor(sample_info$group))
    
    # Filter low-expressed genes
    keep <- filterByExpr(y, min.count = opt$min.count, min.total.count = opt$min.samples)
    y <- y[keep, , keep.lib.sizes = FALSE]
    
    cat("Performing normalization...\n")
    
    # Calculate normalization factors
    y <- calcNormFactors(y, method = opt$norm.method)
    
    # Design matrix
    design <- model.matrix(~0 + group, data = y$samples)
    colnames(design) <- levels(y$samples$group)
    
    cat("Estimating dispersions...\n")
    
    # Estimate dispersions
    y <- estimateDisp(y, design, robust = opt$robust.estimation)
    
    # Fit quasi-likelihood GLM
    fit <- glmQLFit(y, design, robust = opt$robust.estimation, 
                   abundance.trend = opt$abundance.trend)
    
    cat("Performing differential expression test...\n")
    
    # Create contrast
    contrast_name <- paste(comp_groups[1], comp_groups[2], sep = "-")
    contrast <- makeContrasts(contrasts = contrast_name, levels = design)
    
    # Perform quasi-likelihood F-test
    qlf <- glmQLFTest(fit, contrast = contrast)
    
    # Apply Poisson bound if requested
    if (opt$poisson.bound) {
      qlf$table$PValue <- pmax(qlf$table$PValue, 
                              1e-3 * exp(-abs(qlf$table$logFC)))
    }
    
    # Get results
    results <- topTags(qlf, n = Inf, sort.by = "PValue")$table
    results$FDR <- p.adjust(results$PValue, method = "BH")
    
    cat("Writing output files...\n")
    
    # Write all results
    output_file <- paste0(opt$output.prefix, "_results.txt")
    write.table(results, output_file, sep = "\t", quote = FALSE, 
                row.names = TRUE, col.names = NA)
    
    # Write significant results
    sig_results <- results[results$FDR <= opt$fdr.threshold & 
                          abs(results$logFC) >= opt$fold.change.threshold, ]
    
    if (nrow(sig_results) > 0) {
      sig_file <- paste0(opt$output.prefix, "_significant.txt")
      write.table(sig_results, sig_file, sep = "\t", quote = FALSE,
                  row.names = TRUE, col.names = NA)
      
      cat(sprintf("Found %d significant genes (FDR <= %.3f, |logFC| >= %.2f)\n", 
                  nrow(sig_results), opt$fdr.threshold, opt$fold.change.threshold))
    } else {
      cat("No genes met significance criteria\n")
    }
    
    # Generate plots if requested
    if (opt$create.plots) {
      cat("Creating diagnostic plots...\n")
      
      pdf(paste0(opt$output.prefix, "_plots.pdf"), width = 10, height = 8)
      
      # BCV plot
      plotBCV(y, main = "Biological Coefficient of Variation")
      
      # QL dispersion plot
      plotQLDisp(fit, main = "Quasi-Likelihood Dispersion")
      
      # MA plot
      plotMD(qlf, main = paste("MA Plot:", contrast_name))
      abline(h = c(-1, 1), col = "blue", lty = 2)
      
      # Volcano plot
      with(results, plot(logFC, -log10(PValue), pch = 20, 
                        main = paste("Volcano Plot:", contrast_name),
                        xlab = "log2 Fold Change", ylab = "-log10(P-value)"))
      
      # Highlight significant genes
      with(subset(results, FDR <= opt$fdr.threshold & abs(logFC) >= opt$fold.change.threshold),
           points(logFC, -log10(PValue), pch = 20, col = "red"))
      
      # Add significance thresholds
      abline(v = c(-opt$fold.change.threshold, opt$fold.change.threshold), 
             col = "blue", lty = 2)
      abline(h = -log10(0.05), col = "blue", lty = 2)
      
      # MDS plot
      plotMDS(y, main = "Multi-Dimensional Scaling Plot", 
              col = as.numeric(y$samples$group))
      legend("topright", legend = levels(y$samples$group),
             col = 1:nlevels(y$samples$group), pch = 1)
      
      dev.off()
    }
    
    cat("edgeR analysis completed successfully\n")
    return(TRUE)
    
  }, error = function(e) {
    cat(paste("Error in edgeR analysis:", e$message, "\n"), file = stderr())
    traceback()
    return(FALSE)
  })
}

# Main execution
main <- function() {
  # Validate inputs
  if (!validate_inputs(opt)) {
    quit(status = 1)
  }
  
  # Run the analysis
  success <- run_edger_analysis(opt)
  
  # Exit with appropriate status
  quit(status = if(success) 0 else 1)
}

# Execute main function
main()